package com.sajtech.identity.application.registration;

public enum RegistrationError {
  INVALID_ARGUMENT,
  UNSUPPORTED_CHANNEL,
  PHONE_REGISTRATION_DISABLED,
  REQUEST_ID_CONFLICT,
  COMPROMISED_PASSWORD,
  DEPENDENCY_UNAVAILABLE,
  QUOTA_EXCEEDED,
  QUOTA_UNAVAILABLE,
  QUOTA_TIME_SOURCE_UNHEALTHY,
  QUOTA_CAPACITY_UNHEALTHY,
  INVALID_VERIFICATION_CODE,
  RESEND_TOO_SOON
}
