package com.sajtech.identity.application.registration;

public enum RegistrationError {
  INVALID_REGISTRATION_REQUEST,
  PHONE_REGISTRATION_DISABLED,
  PASSWORD_COMPROMISED,
  PASSWORD_SCREENING_UNAVAILABLE,
  QUOTA_EXCEEDED,
  QUOTA_TIME_SOURCE_UNHEALTHY,
  QUOTA_CAPACITY_UNHEALTHY,
  QUOTA_UNAVAILABLE,
  REQUEST_ID_CONFLICT,
  INVALID_REGISTRATION_CHALLENGE,
  REGISTRATION_UNAVAILABLE
}
