package com.sajtech.identity.application.externalidentity;

public enum ExternalIdentityError {
  INVALID_ARGUMENT,
  INVALID_EVIDENCE,
  EVIDENCE_EXPIRED,
  EVIDENCE_REPLAY,
  ACCOUNT_LINK_REQUIRED,
  IDENTITY_ALREADY_LINKED,
  IDENTITY_NOT_LINKED,
  LAST_AUTHENTICATION_METHOD,
  INVALID_SESSION,
  RECENT_AUTH_REQUIRED,
  SESSION_STATE_INVALID
}
