package com.sajtech.identity.application.erasure;

public enum ErasureError {
  INVALID_ARGUMENT,
  INVALID_SESSION,
  RECENT_AUTHENTICATION_REQUIRED,
  MFA_PROOF_REQUIRED,
  MFA_PROOF_INVALID,
  ACTIVE_MEMBERSHIP_EXISTS,
  REQUEST_CONFLICT,
  LEGAL_HOLD_ACTIVE,
  NOT_FOUND,
  FORBIDDEN
}
