spring:
  application:
    name: compromised-password-service
  main:
    banner-mode: "off"
  threads:
    virtual:
      enabled: true

server:
  port: -1
  shutdown: graceful

management:
  server:
    port: 9091
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState,compromisedPasswordDataset
  otlp:
    metrics:
      export:
        enabled: false
  opentelemetry:
    tracing:
      export:
        max-queue-size: 512
        max-batch-size: 128
        schedule-delay: 5s
        timeout: 2s
        otlp:
          connect-timeout: 1s
          timeout: 2s
      limits:
        max-attributes: 32
        max-attribute-value-length: 128
        max-events: 32
        max-links: 16

logging:
  structured:
    format:
      console: logstash
  level:
    root: INFO
