spring:
  application:
    name: compromised-password-service
  main:
    banner-mode: "off"
  threads:
    virtual:
      enabled: true

server:
  port: -1
  shutdown: graceful

management:
  server:
    port: 9091
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState,compromisedPasswordDataset

logging:
  structured:
    format:
      console: logstash
  level:
    root: INFO
