package com.sajtech.identity.application.password;

public enum PasswordError {
  INVALID_ARGUMENT,
  INVALID_CREDENTIALS,
  INVALID_SESSION,
  RECENT_AUTHENTICATION_REQUIRED,
  INVALID_RECOVERY_PROOF,
  RECOVERY_PROOF_EXHAUSTED,
  DEPENDENCY_UNAVAILABLE
}
