package com.sajtech.webbff.application;

public enum BffError {
  RUNTIME_DISABLED,
  INVALID_REQUEST,
  INVALID_ORIGIN,
  FETCH_METADATA_REQUIRED,
  INVALID_SESSION,
  CSRF_INVALID,
  AUTHENTICATION_FAILED,
  TENANT_SELECTION_REQUIRED,
  DEPENDENCY_UNAVAILABLE,
  AUTHORIZATION_DENIED,
  RATE_LIMITED,
  QUOTA_TIME_SOURCE_UNHEALTHY,
  QUOTA_CAPACITY_UNHEALTHY,
  REGISTRATION_REJECTED,
  PASSWORD_REJECTED,
  OIDC_INVALID_RESPONSE,
  OIDC_STATE_INVALID,
  OIDC_UNAVAILABLE,
  ACCOUNT_LINK_REQUIRED,
  EXTERNAL_IDENTITY_REJECTED
}
