package com.sajtech.webbff.application;

public enum BffError {
  RUNTIME_DISABLED,
  INVALID_REQUEST,
  INVALID_ORIGIN,
  FETCH_METADATA_REQUIRED,
  INVALID_SESSION,
  CSRF_INVALID,
  AUTHENTICATION_FAILED,
  TENANT_SELECTION_REQUIRED,
  DEPENDENCY_UNAVAILABLE,
  AUTHORIZATION_DENIED,
  RATE_LIMITED,
  REGISTRATION_REJECTED,
  PASSWORD_REJECTED
}
