apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: {{ include "identity-service.name" . }}
spec:
  selector:
    matchLabels:
      {{- include "identity-service.selectorLabels" . | nindent 6 }}
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: {{ include "identity-service.name" . }}
spec:
  selector:
    matchLabels:
      {{- include "identity-service.selectorLabels" . | nindent 6 }}
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - {{ required "webBff.principal is required" .Values.webBff.principal | quote }}
      to:
        - operation:
            ports: [{{ .Values.service.grpcPort | quote }}]
    {{- if .Values.observability.metrics.enabled }}
    - from:
        - source:
            principals:
              - {{ required "observability.metrics.prometheus.principal is required" .Values.observability.metrics.prometheus.principal | quote }}
      to:
        - operation:
            ports: [{{ .Values.service.managementPort | quote }}]
    {{- end }}
