apiVersion: v1
kind: Service
metadata:
  name: {{ include "identity-service.name" . }}
  labels:
    {{- include "identity-service.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "identity-service.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
    - name: management
      port: {{ .Values.service.managementPort }}
      targetPort: management
      protocol: TCP
