apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | quote }}
  labels:
    {{- include "identity-service.labels" . | nindent 4 }}
automountServiceAccountToken: false
