package com.sajtech.conversation.application;

public enum ConversationError {
  INVALID_REQUEST,
  INVALID_ACCESS_TOKEN,
  AUTHORIZATION_DENIED,
  AUTHORIZATION_UNAVAILABLE,
  CONVERSATION_NOT_FOUND,
  MODEL_RUN_NOT_FOUND,
  CONVERSATION_CONFLICT,
  CONVERSATION_INVALID_STATE,
  TENANT_INACTIVE,
  MODEL_EXECUTION_DISABLED,
  BUDGET_UNAVAILABLE,
  PERSISTENCE_UNAVAILABLE
}
