package com.sajtech.conversation.application;

public enum ConversationError {
  INVALID_REQUEST,
  INVALID_ACCESS_TOKEN,
  AUTHORIZATION_DENIED,
  AUTHORIZATION_UNAVAILABLE,
  CONVERSATION_NOT_FOUND,
  CONVERSATION_CONFLICT,
  CONVERSATION_INVALID_STATE,
  PERSISTENCE_UNAVAILABLE
}
