package com.sajtech.authorization.application;

public enum AuthorizationError {
  AUTHORIZATION_DENIED,
  AUTHORIZATION_UNAVAILABLE,
  AUTHORIZATION_OVERLOADED,
  ROLE_NOT_FOUND,
  ROLE_NAME_CONFLICT,
  SYSTEM_ROLE_IMMUTABLE,
  ROLE_ARCHIVED,
  PERMISSION_UNKNOWN,
  PERMISSION_RETIRED,
  MEMBERSHIP_NOT_ACTIVE,
  TENANT_NOT_AUTHORIZABLE,
  LAST_TENANT_OWNER,
  REQUEST_ID_CONFLICT,
  STALE_ROLE_VERSION,
  LIMIT_EXCEEDED,
  INVALID_ARGUMENT,
  INVALID_ACCESS_TOKEN,
  QUOTA_EXCEEDED,
  QUOTA_UNAVAILABLE
}
