package com.sajtech.identity.application.authentication;

public enum AuthenticationError {
  INVALID_ARGUMENT,
  INVALID_CREDENTIALS,
  INVALID_SESSION,
  REFRESH_REUSE_DETECTED,
  TENANT_SELECTION_REQUIRED,
  AUDIENCE_NOT_ALLOWED,
  QUOTA_EXCEEDED,
  QUOTA_UNAVAILABLE,
  QUOTA_TIME_SOURCE_UNHEALTHY,
  QUOTA_CAPACITY_UNHEALTHY,
  AUTHENTICATION_OVERLOADED,
  SIGNING_KEY_UNAVAILABLE,
  SESSION_STATE_INVALID
}
