spring:
  config:
    import: optional:configtree:/run/secrets/authorization-db-migration/
  flyway:
    enabled: true
    locations: classpath:db/migration
  main:
    web-application-type: none
management:
  endpoint:
    health:
      validate-group-membership: false
