apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-apps-waypoint-options
  namespace: platform-apps
data:
  deployment: |
    spec:
      replicas: 1
      template:
        metadata:
          annotations:
            sidecar.istio.io/proxyImage: docker.io/istio/proxyv2@sha256:2f59eaf91e15213e50d91c7951c81073695872d6b17b82e146773695f24b1c6e
        spec:
          securityContext:
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: istio-proxy
              image: docker.io/istio/proxyv2@sha256:2f59eaf91e15213e50d91c7951c81073695872d6b17b82e146773695f24b1c6e
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: platform-apps-waypoint
  namespace: platform-apps
  labels:
    istio.io/waypoint-for: service
spec:
  infrastructure:
    parametersRef:
      group: ""
      kind: ConfigMap
      name: platform-apps-waypoint-options
  gatewayClassName: istio-waypoint
  listeners:
    - name: mesh
      port: 15008
      protocol: HBONE
