package com.sajtech.identity.application.mfa;

public enum MfaError {
  INVALID_ARGUMENT,
  INVALID_SESSION,
  RECENT_AUTHENTICATION_REQUIRED,
  MFA_NOT_ENABLED,
  INVALID_PROOF,
  CHALLENGE_EXPIRED,
  CHALLENGE_EXHAUSTED,
  REPLAYED_PROOF,
  STATE_CONFLICT,
  QUOTA_EXCEEDED,
  QUOTA_UNAVAILABLE,
  QUOTA_TIME_SOURCE_UNHEALTHY,
  QUOTA_CAPACITY_UNHEALTHY
}
