apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-frontend.name" . }}
  labels:
    {{- include "web-frontend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "web-frontend.selectorLabels" . | nindent 4 }}
  ports:
    - {name: http, port: {{ .Values.service.applicationPort }}, targetPort: http, protocol: TCP}
    - {name: health, port: {{ .Values.service.healthPort }}, targetPort: health, protocol: TCP}
