syntax = "proto3";

package hooshix.compromisedpassword.v1;

import "buf/validate/validate.proto";

option java_multiple_files = true;
option java_package = "com.sajtech.compromisedpassword.contract.v1";

service CompromisedPasswordService {
  rpc LookupPrefix(LookupPrefixRequest) returns (LookupPrefixResponse);
}

message LookupPrefixRequest {
  string prefix = 1 [(buf.validate.field).string = {pattern: "^[0-9A-F]{5}$"}];
}

message CompromisedHashMatch {
  string suffix = 1;
  uint64 occurrence_count = 2;
}

message LookupPrefixResponse {
  repeated CompromisedHashMatch matches = 1;
}
