export const routes = {
  register: '/',
  verify: '/verify',
  login: '/login',
  loginMfa: '/login/mfa',
  tenantSelection: '/tenant-select',
  tenantManagement: '/tenants/manage',
  application: '/application',
  profile: '/profile',
  passwordRecovery: '/password/recovery',
  passwordChange: '/password/change',
  mfa: '/security/mfa',
  externalIdentities: '/security/external-identities',
  accountErasure: '/security/account-erasure',
  oidcComplete: '/oidc/complete',
} as const;
