package com.sajtech.identity.application.tenant;

public enum TenantError {
  INVALID_ARGUMENT,
  INVALID_SESSION,
  TENANT_SLUG_CONFLICT,
  TENANT_NOT_SELECTABLE,
  MEMBERSHIP_NOT_ACTIVE,
  INVITATION_NOT_FOUND,
  INVITATION_NOT_PENDING,
  INVITATION_EXPIRED,
  INVITATION_TARGET_MISMATCH,
  INVITATION_ALREADY_PENDING,
  VERIFIED_CONTACT_REQUIRED,
  AUTHORIZATION_DENIED,
  AUTHORIZATION_UNAVAILABLE,
  LAST_TENANT_OWNER,
  REQUEST_ID_CONFLICT,
  AUDIENCE_NOT_ALLOWED,
  SESSION_STATE_INVALID
}
