package com.sajtech.identity.application.profile;

public enum ProfileError {
  INVALID_ARGUMENT,
  INVALID_SESSION,
  RECENT_AUTHENTICATION_REQUIRED,
  CONTACT_CONFLICT,
  CONTACT_LIMIT_REACHED,
  INVALID_VERIFICATION_CODE,
  VERIFICATION_EXHAUSTED,
  RESEND_TOO_SOON,
  CONTACT_NOT_VERIFIED,
  PRIMARY_CONTACT_REQUIRED,
  REQUEST_ID_CONFLICT,
  NOT_FOUND
}
