apiVersion: v1
kind: PersistentVolume
metadata: {name: compromised-password-dataset-pv}
spec:
  capacity: {storage: 16Mi}
  accessModes: [ReadOnlyMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath: {path: /var/local/hooshix/compromised-password, type: Directory}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - {key: kubernetes.io/hostname, operator: In, values: [platform-local-worker]}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: {name: compromised-password-dataset, namespace: platform-apps}
spec:
  accessModes: [ReadOnlyMany]
  storageClassName: ""
  volumeName: compromised-password-dataset-pv
  resources: {requests: {storage: 16Mi}}
